### PR TITLE
Sf3 compatibility

### PR DESCRIPTION
**Pull request by wasbaiti**
A proposal to make your bundle compatible with symfony 3

### CODE REVIEW

**Comment by malarzm** [comment]
Thank you @wasbaiti for the PR! I haven't got yet to looking into all Symfony 3.0 changes, but would it be possible to have compatibility with 2.7 (or at least 2.8) at the same time?

**Comment by wasbaiti** [comment]
Hello,
I guess it's possible to keep compatibility with 2.7 or higher.
i will fix the unit tests and deploy it next week.

**Comment by malarzm** [comment]
Thank you @wasbaiti, looking forward to!

**Comment by wasbaiti** [comment]
I'm closing this pull request to avoid triggering builds when pushing on my fork project.

**Pull request closed without merging**
